### ISSUE TITLE
Naming of constants

### ISSUE THREAD

**Issue by mayisa87** [Marko-Pajic/SlotMachine#16]
https://github.com/Marko-Pajic/SlotMachine/blob/d649fd957d40aed46b93a2d941c61aea736c828d/Program.cs#L5-L10

Overthink the naming of your constants

GRID_COLUMN it is the column count so it is more like GRID_COLUMN_COUNT same with the row count
the upper bound... upper bound is very unspecific and could mean anything. Isn't it the maximal grid value grid is filled with. So find a better name for that ;)

And still I don't get what the CREDIT_CONVERTER is there for?

**Comment by Marko-Pajic** [comment]
Hi Isabella!
CREDIT_CONVERTOR is the number i multiply cashDeposit with to create playingCredits.
I created playingCredits because Michael told me somehow reduce the wagerAmount for game to be more fun.
I never played slotmachine irl so dont understand what are the rules so i was watching Youtube videos about how slotmachines work and saw that lot of them give you playing credits when you insert actual money in various range from 1:5.
So instead of reducing wagerAmount i incresed "playing amount".
I hope my rumbling makes sense 😅

**Comment by Marko-Pajic** [comment]
And later i use same constant to divide playingCredits before cash out to get money amout that is going to be paid out.

**Comment by mayisa87** [comment]
Ok I see :) thx for the explanation! :)
